name: Enahanced Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node, cache deps
        uses: /.github/actions/cached-deps
        with:
          caching: "true"
      - name: Run Test
        run: npm test
  Building:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: setup node, cache deps
        uses: /.github/actions/cached-deps
        with:
          caching: "true"
      - name: Run Build
        run: npm run build
      - name: Upload Artificat
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  Deploying:
    needs: Building
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output Artifact Content
        run: pwd && ls
      - name: Deploy Code
        run: echo "Deploying..."
