name: Deployment Workflow
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Caching Dependecies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "${{runner.os}}-cache-${{hashFiles('**/pckage.lock.json')}}"
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm test
  Building:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Caching Dependecies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "${{runner.os}}-cache-${{hashFiles('**/pckage.lock.json')}}"
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Upload Artificat
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  Deploying:
    needs: Building
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output Artifact Content
        run: pwd && ls
      - name: Deploy Code
        run: echo "Deploying..."
