name: Exporing Outcome and Conclusion
on: push
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step-one
        run: ech "Hi"
        continue-on-error: true
      - name: step2
        run: echo "${{steps.step-one.outcome}}" && echo ""${{steps.step-one.conclusion}}
