name: Outputs Demo
on:
  workflow_dispatch:
jobs:
  job1:
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Output first output
        run: echo "${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}"
