name: Output Information
on:
  workflow_call:
    inputs:
      artifact-name:
        description: This is the deployable binary
        type: string
        default: dist
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
